include ~/.config/omarchy/current/theme/kitty.conf

font_family      CodeNewRoman Nerd Font Mono
font_size        14

background_opacity 0.95

allow_remote_control yes
confirm_os_window_close 0   
clipboard_control read-clipboard write-clipboard
